### ISSUE TITLE
Sito di scarpe

### ISSUE THREAD

**Issue by tarilabs** [MilanoTechScene/milanotechscene.github.io#25]
Ciao,
il domain .it adesso mostra un sito di scarpe.
Anche http://milanotechscene.github.io fa redirect al sito di scarpe.

**Comment by tarilabs** [comment]
![image](https://user-images.githubusercontent.com/1699252/48010046-1ce6f780-e11d-11e8-80c5-ca7d54140e9e.png)

**Comment by stefanobaghino** [comment]
🔝 😂

**Comment by tarilabs** [comment]
Solved thanks @stefanobaghino
